eureka:
    client:
        serviceUrl:
            defaultZone: ${vcap.services.discovery-service.credentials.uri:http://127.0.0.1:58080}/gateway/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2